# List of verbs of individual Bloom's Taxonomy Level
Knowledge = [
    "Cite",
    "Define",
    "Describe",
    "Draw",
    "Enumerate",
    "Identify",
    "Index",
    "Indicate",
    "Label",
    "List",
    "Match",
    "Meet",
    "Memorize",
    "Name",
    "Outline",
    "Point",
    "Quote",
    "Read",
    "Recall",
    "Recite",
    "Recognize",
    "Record",
    "Repeat",
    "Reproduce",
    "Review",
    "Select",
    "State",
    "Study",
    "Tabulate",
    "Trace",
    "Write"
]
Knowledge = [x.lower() for x in Knowledge]
Comprehension = [
    "Add",
    "Account for",
    "Alter",
    "Annotate",
    "Approximate",
    "Articulate",
    "Associate",
    "Calculate",
    "Change",
    "Characterize",
    "Clarify",
    "Classify",
    "Compare",
    "Compute",
    "Contrast",
    "Convert",
    "Defend",
    "Describe",
    "Detail",
    "Differentiate",
    "Discuss",
    "Distinguish",
    "Elaborate",
    "Estimate",
    "Example",
    "Explain",
    "Express",
    "Extend",
    "Extrapolate",
    "Factor",
    "Generalize",
    "Give",
    "Group",
    "Infer",
    "Interact",
    "Interpolate",
    "Interpret",
    "Locate",
    "Observe",
    "Paraphrase",
    "Picture graphically",
    "Predict",
    "Review",
    "Rewrite",
    "Subtract",
    "Summarize",
    "Translate",
    "Visualize"
]
Comprehension = [x.lower() for x in Comprehension]
Application = [
"Acquire",
"Adapt",
"Allocate",
"Alphabetize",
"Apply",
"Ascertain",
"Assign",
"Attain",
"Avoid",
"Back up",
"Calculate",
"Capture",
"Carry out",
"Change",
"Classify",
"Collect",
"Complete",
"Compute",
"Construct",
"Customize",
"Demonstrate",
"Depreciate",
"Derive",
"Determine",
"Diminish",
"Discover",
"Draw",
"Employ",
"Examine",
"Exercise",
"Explore",
"Expose",
"Express",
"Factor",
"Figure",
"Graph",
"Handle",
"Illustrate",
"Interconvert",
"Investigate",
"Manipulate",
"Modify",
"Operate",
"Outline",
"Personalize",
"Plot",
"Practice",
"Predict",
"Prepare",
"Price",
"Process",
"Produce",
"Project",
"Provide",
"Relate",
"Round off"
"Select",
"Separate",
"Sequence",
"Show",
"Simulate",
"Sketch",
"Solve",
"Sort",
"Subscribe",
"Tabulate",
"Transcribe",
"Translate",
"Use"
]
Application = [x.lower() for x in Application]
Analysis = [
    "Analyze",
    "Audit",
    "Blueprint",
    "Breadboard",
    "Break down",
    "Categorize",
    "Characterize",
    "Classify",
    "Compare",
    "Compute",
    "Confirm",
    "Contrast",
    "Correlate",
    "Detect",
    "Diagnose",
    "Diagram",
    "Differentiate",
    "Discriminate",
    "Dissect",
    "Distinguish",
    "Document",
    "Ensure",
    "Examine",
    "Explain",
    "Explore",
    "Figure out",
    "File",
    "Group",
    "Identify",
    "Illustrate",
    "Infer",
    "Interrupt",
    "Inventory",
    "Investigate",
    "Layout",
    "Manage",
    "Maximize",
    "Minimize",
    "Optimize",
    "Order",
    "Outline",
    "Point out",
    "Prioritize",
    "Proofread",
    "Query",
    "Relate",
    "Select",
    "Separate",
    "Size",
    "Sort",
    "Subdivide",
    "Train",
    "Transform"
]
Analysis = [x.lower() for x in Analysis]
Synthesis = [
    "Abstract",
    "Animate",
    "Arrange",
    "Assemble",
    "Budget",
    "Categorize",
    "Code",
    "Combine",
    "Compile",
    "Compose",
    "Construct",
    "Cope",
    "Correspond",
    "Create",
    "Cultivate",
    "Debug",
    "Depict",
    "Design",
    "Develop",
    "Devise",
    "Dictate",
    "Enhance",
    "Explain",
    "Facilitate",
    "Format",
    "Formulate",
    "Generalize",
    "Generate",
    "Handle",
    "Import",
    "Improve",
    "Incorporate",
    "Integrate",
    "Interface",
    "Join",
    "Lecture",
    "Model",
    "Modify",
    "Network",
    "Organize",
    "Outline",
    "Overhaul",
    "Plan",
    "Portray",
    "Prepare",
    "Prescribe",
    "Produce",
    "Program",
    "Propose",
    "Rearrange",
    "Reconstruct",
    "Relate",
    "Reorganize",
    "Revise",
    "Rewrite",
    "Specify",
    "Summarize",
    "Write"
]
Synthesis = [x.lower() for x in Synthesis]
Evaluation = [
    "Arbitrate",
    "Appraise",
    "Assess",
    "Award",
    "Choose",
    "Compare",
    "Conclude",
    "Contrast",
    "Counsel",
    "Criticize",
    "Critique",
    "Defend",
    "Determine",
    "Discriminate",
    "Estimate",
    "Evaluate",
    "Explain",
    "Grade",
    "Hire",
    "Interpret",
    "Judge",
    "Justify",
    "Measure",
    "Predict",
    "Prescribe",
    "Prioritize",
    "Rank",
    "Rate",
    "Recommend",
    "Release",
    "Select",
    "Summarize",
    "Support",
    "Test",
    "Validate",
    "Verify"
]
Evaluation = [x.lower() for x in Evaluation]

# List of all Levels
bloom = [Knowledge, Comprehension, Application, Analysis, Synthesis, Evaluation]

# Number and Level Dictionary
level = {'0': 'Knowledge (C1)',
         '1': 'Comprehension (C2)',
         '2': 'Application (C3)',
         '3': 'Analysis (C4)',
         '4': 'Synthesis (C5)',
         '5': 'Evaluation (C6)'
}
